branches:
  only:
    - master

sudo: required
services:
  - docker

before_install:
  - docker build -t portlipedia-test -f Dockerfile.dev .

script: 
  - docker run portlipedia-test

after_success:
  - docker build -t 0xcodes/portlipedia .
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 0xcodes/portlipedia