branches:
  only:
    - master

sudo: required
services:
  - docker

before_install:
  - docker build -t portlipedia-test -f Dockerfile.dev .

script: 
  - docker run portlipedia-test

after_success:
  - docker build -t portlipedia .
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --passwd-stdin
  - docker push portlipedia